# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='友链名称', max_length=255, verbose_name='友链名称')),
                ('type', models.IntegerField(choices=[(1, '友情链接'), (2, '合作伙伴')], default=1, help_text='友链类型：1友情链接 2合作伙伴', verbose_name='友链类型：1友情链接 2合作伙伴')),
                ('url', models.CharField(default=None, help_text='友链URL', max_length=255, null=True, verbose_name='友链URL')),
                ('item_id', models.IntegerField(default=0, help_text='站点ID', verbose_name='站点ID')),
                ('cate_id', models.IntegerField(default=0, help_text='栏目ID', verbose_name='栏目ID')),
                ('platform', models.IntegerField(choices=[(1, 'PC站'), (2, 'WAP站'), (3, '微信小程序'), (4, 'APP应用')], default=1, help_text='投放平台：1PC站 2WAP站 3微信小程序 4APP应用', verbose_name='投放平台：1PC站 2WAP站 3微信小程序 4APP应用')),
                ('form', models.IntegerField(choices=[(1, '文字链接'), (2, '图片链接')], default=1, help_text='友链形式：1文字链接 2图片链接', verbose_name='友链形式：1文字链接 2图片链接')),
                ('image', models.CharField(help_text='友链图片', max_length=255, verbose_name='友链图片')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='友链状态：1-正常 2-停用', verbose_name='友链状态：1-正常 2-停用')),
                ('sort', models.IntegerField(default=0, help_text='友链顺序', verbose_name='友链顺序')),
                ('note', models.CharField(help_text='友链备注', max_length=255, null=True, verbose_name='友链备注')),
            ],
            options={
                'verbose_name': '友链表',
                'verbose_name_plural': '友链表',
                'db_table': 'django_link',
            },
        ),
    ]
