# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='广告标题', max_length=255, verbose_name='广告标题')),
                ('sort_id', models.IntegerField(default=0, help_text='广告ID', verbose_name='广告ID')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '文字'), (3, '视频'), (4, '推荐')], default=0, help_text='广告类型：1图片 2文字 3视频 4推荐', verbose_name='广告类型：1图片 2文字 3视频 4推荐')),
                ('cover', models.CharField(help_text='广告封面', max_length=255, null=True, verbose_name='广告封面')),
                ('url', models.CharField(help_text='广告地址', max_length=255, null=True, verbose_name='广告地址')),
                ('width', models.IntegerField(default=0, help_text='广告宽度', verbose_name='广告宽度')),
                ('height', models.IntegerField(default=0, help_text='广告高度', verbose_name='广告高度')),
                ('start_time', models.DateTimeField(help_text='开始时间', max_length=11, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间', max_length=11, null=True, verbose_name='结束时间')),
                ('click', models.IntegerField(default=0, help_text='点击率', verbose_name='点击率')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='广告状态：1-正常 2-停用', verbose_name='广告状态：1-正常 2-停用')),
                ('note', models.CharField(help_text='广告备注', max_length=255, null=True, verbose_name='广告备注')),
                ('sort', models.IntegerField(default=0, help_text='广告排序', verbose_name='广告排序')),
                ('content', models.TextField(help_text='广告标题', null=True, verbose_name='广告标题')),
            ],
            options={
                'verbose_name': '广告表',
                'verbose_name_plural': '广告表',
                'db_table': 'django_ad',
            },
        ),
    ]
