# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, help_text='用户ID', verbose_name='用户ID')),
                ('role_id', models.IntegerField(default=0, help_text='角色ID', verbose_name='角色ID')),
            ],
            options={
                'verbose_name': '用户角色表',
                'verbose_name_plural': '用户角色表',
                'db_table': 'django_user_role',
            },
        ),
    ]
