# Generated by Django 4.1.3 on 2023-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='菜单标题', max_length=150, verbose_name='菜单标题')),
                ('icon', models.CharField(help_text='菜单图标', max_length=50, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(default=0, help_text='上级ID', verbose_name='上级ID')),
                ('path', models.CharField(help_text='菜单路径', max_length=255, null=True, verbose_name='菜单路径')),
                ('component', models.CharField(help_text='菜单组件', max_length=255, null=True, verbose_name='菜单组件')),
                ('target', models.CharField(help_text='打开方式', max_length=30, verbose_name='打开方式')),
                ('permission', models.CharField(help_text='权限节点', max_length=150, verbose_name='权限节点')),
                ('type', models.IntegerField(default=0, help_text='菜单类型：0-菜单 1-节点', verbose_name='菜单类型：0-菜单 1-节点')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='菜单状态：1-正常 2-停用', verbose_name='菜单状态：1-正常 2-停用')),
                ('hide', models.IntegerField(choices=[(0, '可见'), (1, '不可见')], default=1, help_text='是否可见：0-可见 1-不可见', verbose_name='是否可见：0-可见 1-不可见')),
                ('sort', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('note', models.CharField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'db_table': 'django_menu',
            },
        ),
    ]
