# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='部门名称', max_length=150, verbose_name='部门名称')),
                ('code', models.CharField(help_text='部门编码', max_length=150, verbose_name='部门编码')),
                ('type', models.IntegerField(default=0, help_text='部门类型：1-公司 2-子公司 3-部门 4-小组', verbose_name='部门类型：1-公司 2-子公司 3-部门 4-小组')),
                ('pid', models.IntegerField(default=0, help_text='上级部门ID', verbose_name='上级部门ID')),
                ('sort', models.IntegerField(default=0, help_text='部门排序', verbose_name='部门排序')),
                ('note', models.CharField(default='', help_text='备注', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 'django_dept',
                'ordering': ('sort',),
            },
        ),
    ]
