# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='字典项名称', max_length=150, verbose_name='字典项名称')),
                ('value', models.CharField(help_text='字典项值', max_length=150, verbose_name='字典项值')),
                ('dict_id', models.IntegerField(default=0, help_text='字典ID', verbose_name='字典ID')),
                ('note', models.CharField(help_text='字典项备注', max_length=255, null=True, verbose_name='字典项备注')),
                ('sort', models.IntegerField(default=0, help_text='字典项顺序', verbose_name='字典项顺序')),
            ],
            options={
                'verbose_name': '字典项表',
                'verbose_name_plural': '字典项表',
                'db_table': 'django_dict_data',
            },
        ),
    ]
