# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(blank=True, db_column='name', help_text='会员等级名称', max_length=150, verbose_name='会员等级名称')),
                ('sort', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '会员等级表',
                'verbose_name_plural': '会员等级表',
                'db_table': 'django_member_level',
                'ordering': ('sort',),
            },
        ),
    ]
