# Generated by Django 4.1.3 on 2023-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('role_id', models.IntegerField(default=0, help_text='角色ID', verbose_name='角色ID')),
                ('menu_id', models.IntegerField(default=0, help_text='菜单ID', verbose_name='菜单ID')),
            ],
            options={
                'verbose_name': '角色菜单表',
                'verbose_name_plural': '角色菜单表',
                'db_table': 'django_role_menu',
            },
        ),
    ]
