# Generated by Django 4.1.3 on 2023-02-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenu',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='rolemenu',
            name='update_user',
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
