# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('title', models.CharField(help_text='配置项标题', max_length=150, verbose_name='配置项标题')),
                ('code', models.CharField(help_text='配置项编码', max_length=150, verbose_name='配置项编码')),
                ('value', models.CharField(help_text='配置项值', max_length=1000, verbose_name='配置项值')),
                ('options', models.CharField(help_text='配置选项', max_length=255, verbose_name='配置选项')),
                ('config_id', models.IntegerField(default=0, help_text='配置ID', verbose_name='配置ID')),
                ('type', models.CharField(help_text='配置类型', max_length=150, verbose_name='配置类型')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='配置状态：1-正常 2-停用', verbose_name='配置状态：1-正常 2-停用')),
                ('sort', models.IntegerField(default=0, help_text='配置项顺序', verbose_name='配置项顺序')),
                ('note', models.CharField(help_text='配置项备注', max_length=255, null=True, verbose_name='配置项备注')),
            ],
            options={
                'verbose_name': '配置项表',
                'verbose_name_plural': '配置项表',
                'db_table': 'django_config_data',
            },
        ),
    ]
