# Generated by Django 4.1.3 on 2023-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='站点名称', max_length=150, verbose_name='站点名称')),
                ('type', models.IntegerField(choices=[(1, '普通站点'), (2, '其他站点')], default=1, help_text='站点类型：1普通站点 2其他站点', verbose_name='站点类型：1普通站点 2其他站点')),
                ('url', models.CharField(help_text='站点地址', max_length=255, null=True, verbose_name='站点地址')),
                ('image', models.CharField(help_text='站点图片', max_length=255, null=True, verbose_name='站点图片')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, help_text='站点状态：1-正常 2-停用', verbose_name='站点状态：1-正常 2-停用')),
                ('note', models.CharField(help_text='站点备注', max_length=255, null=True, verbose_name='站点备注')),
                ('sort', models.IntegerField(default=0, help_text='站点顺序', verbose_name='站点顺序')),
            ],
            options={
                'verbose_name': '站点表',
                'verbose_name_plural': '站点表',
                'db_table': 'django_item',
            },
        ),
    ]
